/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package usermanagement;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import salesmanagement.DailySalesEntry;
import salesmanagement.itementry;
import salesmanagement.prFrame;
import salesmanagement.supplierentry;

/**
 *
 * @author yingx
 */
public class smpage extends javax.swing.JFrame {

    /**
     * Creates new form smpage
     */
    public smpage() {
        //initComponents();
        setTitle("OWSB Purchase Order Management System");
        setSize(500, 400);
        setLayout(null);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);

        JLabel title = new JLabel("Main Menu", SwingConstants.CENTER);
        title.setBounds(100, 30, 300, 40);
        title.setFont(new java.awt.Font("Segoe UI", 1, 24));
        add(title);

        JButton btnItem = new JButton("Item Management");
        btnItem.setBounds(150, 100, 200, 40);
        add(btnItem);

        JButton btnSupplier = new JButton("Supplier Management");
        btnSupplier.setBounds(150, 150, 200, 40);
        add(btnSupplier);

        JButton btnSales = new JButton("Daily Sales Entry");
        btnSales.setBounds(150, 200, 200, 40);
        add(btnSales);
        
        JButton btnPr = new JButton("PR Entry");
        btnPr.setBounds(150, 250, 200, 40);
        add(btnPr);

        JButton btnExit = new JButton("Exit");
        btnExit.setBounds(150, 300, 200, 40);
        add(btnExit);

        // Action Listeners
        btnItem.addActionListener(e -> {
            new itementry().setVisible(true);
            dispose();
        });

        btnSupplier.addActionListener(e -> {
            new supplierentry().setVisible(true);
            dispose();
        });

        btnSales.addActionListener(e -> {
            new DailySalesEntry().setVisible(true);
            dispose();
        });
        
        btnPr.addActionListener(e -> {
            new prFrame().setVisible(true);
            dispose();
        });

        btnExit.addActionListener(e -> System.exit(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(smpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(smpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(smpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(smpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new smpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
